---
- hosts: all
  become: yes
  tasks:
    - name: Update repositories cache and install "foo" package
      apt:
        name: "{{item}}"
      with_items:
          - python-pip
          - apache2
          - apache2-utils
          - libapache2-mod-wsgi
    - pip:
        name: "{{item}}"
      with_items:
          - pypiserver
          - passlib
    - htpasswd:
        path: /home/vagrant/htpasswd.txt
        name: testuser
        password: 'testpassword'
        owner: www-data
        group: www-data
        mode: 0640
    - name: Creates directory
      file: path=/home/vagrant/packages state=directory owner=www-data group=www-data

    - name: example copying file with owner and permissions
      template:
        src: templates/pypiserver.wsgi
        dest: "/home/{{ansible_ssh_user}}/packages/pypiserver.wsgi"
        owner: www-data
        group: www-data

    - name: example copying file with owner and permissions
      template:
        src: templates/pypiserver.conf
        dest: /etc/apache2/sites-available/pypiserver.conf

    - apache2_module:
        state: present
        name: wsgi

    - name: Rolling back - Removing out virtualhost
      command: a2dissite 000-default.conf

    - name: Rolling back - Removing out virtualhost
      command: a2ensite pypiserver.conf

    - name: Start service httpd, if not running
      service:
         name: apache2
         state: restarted


